# SPDX-License-Identifier: MIT
# Copyright (C) 2026 VIKINGYFY

#CI项目
name: DEFAULT

#CI计划
on:
  #手动编译
  workflow_dispatch:
    inputs:
      DEVICE:
        description: '选择编译设备'
        required: true
        default: 'JD-AX6600-WIFI'
        type: choice
        options:
          - JD-AX6600-WIFI
          - GL-MT6000-WIFI
          - CMIOT-AX18-NOWIFI
      PACKAGE:
        description: '手动调整插件包，多个请用\n符号隔开。'
        required: false
        type: string
      TEST:
        description: '仅输出配置文件，不编译固件。'
        default: 'false'
        required: false
        type: boolean
      PACKAGE_MANAGER:
        description: '包管理器类型'
        required: true
        default: 'apk'
        type: choice
        options:
          - ipk
          - apk
      UPLOAD_TYPE:
        description: '固件上传方式'
        required: true
        default: 'release'
        type: choice
        options:
          - release
          - artifact
      FIREWALL:
        description: '防火墙版本'
        required: true
        default: 'fw4'
        type: choice
        options:
          - fw3
          - fw4
      DEFAULT_LANIP:
        description: '默认登录地址'
        required: true
        default: '192.168.0.1'

#CI权限
permissions: write-all

#CI任务
jobs:
  config:
    name: ${{inputs.DEVICE}}-${{inputs.FIREWALL}}
    strategy:
      fail-fast: false

    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      WRT_CONFIG: ${{inputs.DEVICE}}
      WRT_THEME: aurora
      WRT_NAME: Linjw
      WRT_SSID: LEDE
      WRT_WORD: none
      WRT_IP: ${{inputs.DEFAULT_LANIP}}
      WRT_PW: ' '
      WRT_REPO: https://github.com/VIKINGYFY/immortalwrt.git
      WRT_BRANCH: main
      WRT_SOURCE: VIKINGYFY/immortalwrt
      WRT_PACKAGE: ${{inputs.PACKAGE}}
      WRT_TEST: ${{inputs.TEST}}
      WRTPackageManager: ${{inputs.PACKAGE_MANAGER}}
      UPLOAD_TYPE: ${{inputs.UPLOAD_TYPE}}
      WRT_FIREWALL: ${{inputs.FIREWALL}}
